@startuml
title Диаграмма контейнеров
top to bottom direction

!include ../c4_templates/C4_Container.puml

Person(user, "Пользователь", "Управляет отоплением и мониторит температуру")
Person(admin, "Администратор", "Администрирует систему")

System_Boundary(app, "Приложение Умный дом") {
    Container(mobileApp, "Мобильное приложение", "Предоставляет пользователю доступ к системе через мобильное приложение")
    Container(webApp, "Веб сайт", "Предоставляет пользователю доступ к системе через сайт")
    Container(backend, "Backend", "Бэкэндовая часть приложения, отвечает за обработку запросов и сбор данных")
    ContainerDb(db, "Базы данных", "Хранение данных приложения")
}

Container_Ext(devices, "Устройства", "Устройства умного дома, установленные у пользователей")

Rel(user, mobileApp, "Использует мобильное приложение")
Rel(user, webApp, "Использует вебсайт")
Rel(admin, webApp, "Использует админку приложения")
Rel(mobileApp, backend, "Направляет запросы пользователя для обработки")
Rel(webApp, backend, "Направляет запросы пользователя для обработки")
BiRel_L(backend, db, "Сохраняет и получает постоянно хранимые данные")
Rel(backend, devices, "Отправляет запросы и команды пользователей")
Rel(devices, backend, "Получает данные в ответ и собирает телеметрию")

@enduml